export const GET_LOCATIONS_ACTION = 'GET_LOCATIONS_ACTION';
export const GET_LOCATIONS_REDUCER = 'GET_LOCATIONS_REDUCER';

export const GET_FORECAST_ACTION = 'GET_FORECAST_ACTION';
export const GET_FORECAST_REDUCER = 'GET_FORECAST_REDUCER';

export const GET_SELECTED_CITY_WEATHER_FORECAST_ACTION = 'GET_SELECTED_CITY_WEATHER_FORECAST_ACTION';
export const GET_SELECTED_CITY_WEATHER_FORECAST_REDUCER = 'GET_SELECTED_CITY_WEATHER_FORECAST_REDUCER';
